# Generated by Django 3.0.8 on 2020-10-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_f_name', models.CharField(max_length=30)),
                ('s_l_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.IntegerField(unique=True)),
                ('password', models.CharField(max_length=8)),
                ('con_password', models.CharField(max_length=8)),
            ],
        ),
    ]
