# Generated by Django 3.0.8 on 2021-01-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_studentmodal_upload_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodal',
            name='upload_img',
            field=models.ImageField(default=False, upload_to='student/'),
        ),
    ]
