# Generated by Django 3.0.8 on 2021-01-10 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20210110_1455'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetailsModal',
        ),
    ]
